### ISSUE TITLE
fixtures for delegated type

### ISSUE THREAD

**Issue by wdiechmann** [minitest/minitest#910]
I'm used to setting fixtures for polymorphic associations like

```
# assets.yml
one:
  name: Product 1
  assetable: one (Product)

two:
  name: Tool 2
  state: mint
  assetable_id: wrench
  assetable_type: Tool

wrench_broken:
  name: Tool 2
  state: Broken
  assetable: wrench (Tool)

# tools.yml
wrench:
  size: 2

# asset.rb
class Asset < ApplicationRecord 
  belongs_to :assetable, polymorphic: true
```

But after I started using 

```
# asset.rb
class Asset < ApplicationRecord
  delegated_type :assetable, types: %w[ Product Tool ], dependent: :destroy

# tool.rb
class Tool < ApplicationRecord 
  has_one :asset, as: :assetable, touch: true, dependent: :destroy

```

I am no longer able to use my fixtures like

```
  @asset = assets(:two)
  @tool = tools(:wrench)
  @broken_tool = assets(:wrench_broken)
  assert_equal @asset.assetable, @tool
  assert_equal @broken_tool.assetable, @tool
```
